"""update status for user

Revision ID: 0a5ad1d40108
Revises: a1a06d95c1a3
Create Date: 2020-05-30 21:10:26.291360

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a5ad1d40108'
down_revision = 'a1a06d95c1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user', 'status')
    # ### end Alembic commands ###
