"""empty message

Revision ID: 2cdcb757b5ff
Revises: 42d4c8c2cf33
Create Date: 2020-06-05 17:05:56.871654

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2cdcb757b5ff'
down_revision = '42d4c8c2cf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'telegram_chat', ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_chat', type_='unique')
    op.drop_column('telegram_chat', 'chat_id')
    # ### end Alembic commands ###
