"""empty message

Revision ID: 42d4c8c2cf33
Revises: a11e2d7b876b
Create Date: 2020-06-05 17:04:36.384206

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42d4c8c2cf33'
down_revision = 'a11e2d7b876b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_chat_chat_id_key', 'telegram_chat', type_='unique')
    op.drop_column('telegram_chat', 'chat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chat', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('telegram_chat_chat_id_key', 'telegram_chat', ['chat_id'])
    # ### end Alembic commands ###
