"""Initial migration.

Revision ID: a1a06d95c1a3
Revises: 4a1c52f3846d
Create Date: 2020-05-30 20:06:19.226934

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a1a06d95c1a3'
down_revision = '4a1c52f3846d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id'),
                    sa.UniqueConstraint('username')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('user_id', name='user_user_id_key'),
                    sa.UniqueConstraint('username', name='user_username_key')
                    )
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
